### ISSUE TITLE
Issue with dwains dark theme

### ISSUE THREAD

**Issue by fwmarcel** [dwainscheeren/dwains-lovelace-dashboard#318]
first a thank you for the great work.

But now to the actual problem:

when i open dwains-dashboard directly, be it in the app or in the browser, the background of the dark theme is bright.
See image...

![image](https://user-images.githubusercontent.com/22275913/125847635-9b04f132-64a2-4280-afdf-c39f415161d6.png)

if i do a reload and am on another "normal" Home Assistant Lovelace page and from there switch to dwains-dashboard the background is dark as desired.
see picture...

![image](https://user-images.githubusercontent.com/22275913/125848334-b819ab11-8932-47c0-a06e-1972f5f364c3.png)

for this reason i hope to find a solution to the problem here

**Comment by HairyHook** [comment]
Hello,

I have encountered this problem recently, and the way I fixed it was to set Dwains Dashboard as default dashboard in my user profile. From the picture, I see that you have the "Overview" on top, so most likely that one is your default. Click on User (lower left corner) - Dashboard - Dwains Dashboard as default. 

Hope it helps with your issue.

**Comment by dwainscheeren** [comment]
You can fix this by installing this theme https://github.com/dwainscheeren/dwains-dashboard-addons/tree/master/lovelace_theme

**Comment by fwmarcel** [comment]
@HairyHook thanks for your help. On my Mobile Devices I have set Dwains Dashboard as default. But the Problem stays.

**Comment by fwmarcel** [comment]
@dwainscheeren I have already reinstalled this theme. In last week. Is there a update?

**Comment by TheGroundZero** [comment]
Fresh install of Dwains Dashboard and Dwains Dark Theme, Dwains Dashboard set to default dashboard and user's theme set to Dwains Dark Theme.
Yet I still get the light background in the dashboard.

Marcel's fix of reloading and first opening a different page doesn't work
![image](https://user-images.githubusercontent.com/2406013/144242441-500f4ef7-fe70-4681-9ce8-03a4816e5340.png)

**Comment by jasonajack** [comment]
@TheGroundZero Have you found a fix for this yet? I'm seeing the same issue.

**Comment by TheGroundZero** [comment]
> @TheGroundZero Have you found a fix for this yet? I'm seeing the same issue.

I never really figured it out.
Sometimes it worked, sometimes it didn't. Sometimes hard browser refresh fixed it, sometimes it didn't.

Moved away from DD and back to customising my own Lovelace dashboards, so can't test with 2022.2 anymore.

**Comment by dwainscheeren** [comment]
This is fixed weeks ago. You must set an theme in the dd integrations settings and set your own lovelace theme to default or backend selected. Then it works.

**Comment by jasonajack** [comment]
> This is fixed weeks ago. You must set an theme in the dd integrations settings and set your own lovelace theme to default or backend selected. Then it works.

I think this is what I was missing. I had set the dark theme theme in my own profile and did not see the option to configure from the Integrations settings. After I set to dark theme I had to restart the service and Ctrl-F5 to see the new theme show.

Thank you for your help!
