### ISSUE TITLE
Gauges don‘t show values 

### ISSUE THREAD

**Issue by sven0110** [dwainscheeren/dwains-lovelace-dashboard#473]
I‘ve a fresh installation of DD3 and runing HA in Docker ( core-2022.4.7 ).

If i reload DD3, start HA App (iOS) or switch between areas the Gauge Display no values.
They show values if the value is updating or i reload the area. 
It doesn‘t matter of the values come from mqtt, hue sensors (temperatur) or other elements.
![8A10D00C-719B-4EF6-827F-F36008AE2104](https://user-images.githubusercontent.com/81709989/165346273-92f74625-7bc0-407d-974b-1fc4d353f969.png)
![9BDB77B3-51B4-49BF-A6EF-B0299A6E4793](https://user-images.githubusercontent.com/81709989/165346287-df23fc83-1928-4d24-b963-8cd2b214a4ba.png)
![EBEA2CF7-8958-4295-A645-0E88AB9CCE1C](https://user-images.githubusercontent.com/81709989/165346290-8acef9ce-4628-4cb1-89a7-aef204ac7ddc.png)

**Comment by sven0110** [comment]
Hi!

I‘ve tested the Gauge Cards also with Safari and Firefox and get the same issue. The values of the cards are only visible if I reload the page or the value is changing in the next moment e.g. temperature or photovoltaic.
If you need more infos please let me know.
Thanks in advance and greetings, Sven

**Comment by dwainscheeren** [comment]
Seems like an issue with the integration from creator of that card

**Comment by sven0110** [comment]
Ok…thanks for your reply but it‘s the out of the box HA Gauge card or is there another way to display the values like this?

**Comment by Goodwillson** [comment]
I am getting same issue with gauge graphs, is fix comming soon?

**Comment by thab-schreck** [comment]
Can also confirm the bug. What I found out is that changing any css property of the "value-text" in the svg also makes the value visible again.

**Comment by thab-schreck** [comment]
> Can also confirm the bug. What I found out is that changing any css property of the "value-text" in the svg also makes the value visible again.

Also tested it in two other "normal" dashboards, and it's working like a charm there. So must be related to dwains dashboard in any way 🤔

**Comment by thab-schreck** [comment]
Digged more into it. Seems to be a problem with the viewbox of the svg text.
This is just after entering the area in which the gauge is placed (with invisible Text).
![image](https://user-images.githubusercontent.com/125572023/221327142-e14025ae-ab2d-4b4b-ae9b-551c175e6e49.png)

This is after the value of the sensor gets a new value:
![image](https://user-images.githubusercontent.com/125572023/221327085-ce9bccb9-f9b5-4930-bc32-5515828e364e.png)

This can be tested if you copy the viewbox value when the text is visible and copy it over after it is invisible.

Seems that the text is beeing displayed "off-screen" before and on the update it gets rendered at the correct position. Might be a problem with lifecycles. Didn't look up dwains code and do not know how or when he renders the elements. But that could be the place where I would start searching.

**Comment by Duke194** [comment]
I have played a little around with the gauge in dwains dashboard. Seems to be a problem with the SVG text. It is not placed in the right place when entering the area in which the gauge is placed. If you inspect the HTML tree, you will see that the viewBox is all 0.
![image](https://user-images.githubusercontent.com/16086934/221327598-2263b595-907c-4be5-92ad-5e59b406d029.png)

When the value gets updated, the viewBox value is corrected and the text is visible again.
![image](https://user-images.githubusercontent.com/16086934/221327623-59207355-327e-4dfd-9834-1e524de45b73.png)

I have tested and confirmed that you can "fix" the issue by copying the correct placement over the viewBox property. This is just temporary, but confirms that this is the problem.

It's likely a lifecycle issue, I suspect when entering a new area all items are being loaded. At the point when the gauge is loaded it might not be rendered already and therefore the text gets the wrong placement and puts the text at 0. But that's just a guess, which I have not looked up in dwains code. It's just the place where I would start looking up the problem.

**Comment by rubenrivera8** [comment]
Just following up on this hoping for a fix in future update release, as this bug is still present in v3.4.3.

**Comment by dwainscheeren** [comment]
Thanks for reporting this.

Dwains Dashboard 3.9.0 has now been released, and the source files for DD3 are available in this repository.

DD3 is no longer under active feature development and will slowly be phased out. Active development continues in Dwains Dashboard Next:
https://github.com/dwainscheeren/dwains-dashboard-next

At the time of writing, Dwains Dashboard Next is still in alpha.

If this issue is a feature request, please check whether it fits Dwains Dashboard Next instead.

If this issue is a bug, please retest with DD3 version 3.9.0. If the bug is still reproducible there, please open a new issue with:

- Home Assistant version
- Dwains Dashboard version
- browser and device
- browser console errors
- clear reproduction steps

For more context, see #906.

For that reason, this older issue is being closed as part of the DD3 issue tracker cleanup.
