### ISSUE TITLE
After 2023.9 update - Custom element doesn't exist

### ISSUE THREAD

**Issue by rosicenko** [dwainscheeren/dwains-lovelace-dashboard#726]
So yesterday I updated HA core to 2023.9. And after that I have problem to load dashboard. Worst case is android app. Even after clean cache, relogin, restart I receive "Custom element doesn't exist: homepage-card." Same for devices-card, ...

If I reinstall the android app it works just for a while and breaks again.

I tried:
multiple cache cleaning
webview cache cleaning
relogin
redownloading via HACS
multiple device restarts
reinstall of the app
different devices
cloudflare cache purge

Same happens in Chrome for desktop, but here is cache purge more useful. But it also last just for a while until it stops to work again.

Any ideas what to do? Thanks in advance

**Comment by dwainscheeren** [comment]
It seems that 2023.9 breaks DD. I need to look into this

**Comment by ctqctq** [comment]
![Screenshot 2023-09-07 121432](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/8980542/3b7d826d-47f0-4911-9d28-bbb5ec9e6cd0)
![Screenshot 2023-09-07 121933](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/8980542/b974801d-120b-49c0-b4c6-fd08aeeca2c4)

Looks like loadcardhelpers() is undefined

**Comment by ctqctq** [comment]
the loadCardHelpers() is added to window in ha-panel-lovelace.ts
so maybe adding customElements.whenDefined('ha-panel-lovelace') to the bases2 array?

**Comment by ctqctq** [comment]
> 
Confirmed
Adding customElements.whenDefined('ha-panel-lovelace') seems to work on my end.

**Comment by Alona23** [comment]
I currently have the same issue with DD not installing from my QNAP virtual station, but it works from my android phone.


![DD](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/125964201/77f74fd4-fb2f-41e6-8dab-89bcdcf00dab)

**Comment by KruseLuds** [comment]
I had the same error but just now when I went back to also post a screenshot (just before I saw yours above @Alona23 ), the issue disappeared... lol!  Maybe it is intermittent rather than all the time...

**Comment by doktordoc1** [comment]
Same here, any solution ?

**Comment by TrialMaster** [comment]
No issues with Windows 11 and iOS devices.

**Comment by doktordoc1** [comment]
I am on Android and Win 10

**Comment by ParrottRepairs** [comment]
I have been having this same thing as well. Win 10 and Android have an issue but iOS seems to work normally.
![Screenshot 2023-09-09 081114](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/111465524/01dfd3b1-8428-48b7-a6a7-1256ee90808d)
1st load is the same but then it's slightly different on a refresh...
![Screenshot 2023-09-09 081249](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/111465524/cb69e5ac-6b34-4109-ac4f-82b85882e7a7)

**Comment by guidog66** [comment]
Here it's not working on Windows 11 (Edge browser) and in the Android app. Also not working in the Fully Kiosk Browser.

However, it is working for me in the Edge browser on Android on my Galaxy tab s9+, but not in the Edge Browser on my S21FE phone.

Next day: also not working anymore on tab s9+

**Comment by jakesie1309** [comment]
Tested on Firefox and working fine, however as above, not working on Edge. No issues with the mobile app on iPhone.

**Comment by jakesie1309** [comment]
> Same here, any solution ?

I needed to downgrade to 2023.8.4 All works fine on the pervious version.
You can use the below code in terminal in your HA instance to downgrade:  `ha core update --version 2023.8.4`

**Comment by dwainscheeren** [comment]
I will try to take a look at it tomorrow

**Comment by FSHelgeland** [comment]
I have the same from time to time. It happens on mac with different browsers. It happens on my old iPad Air2 , but havent experienced it on my iphone 13 mini yet. Several refreshes and its good to go.

**Comment by renaatdb** [comment]
Tested on Firefox and working fine, however as above, not working on Edge or Chrome. No issues with the mobile app on android.

**Comment by jamstruth** [comment]
Running HA Container Build 2023.9.1 - DD 3.4.3 is still working for me across Chrome and Android Apps. 
Maybe this is limited to HAOS and Core somehow?

**Comment by Grauwulf75** [comment]
Working mostly OK for me on Chrome/Win 10, and no issues with the Android app. However, the Samsung web browser on our Tizen powered smart fridge is not, even with clearing all caches, etc.

**Comment by derekcentrico** [comment]
Following.  Same sort of issue.  Didn't know not to upgrade to 9.1 from 8.4.

<img width="344" alt="image" src="https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/1930094/09c570c5-6aec-46f9-975b-3971976fd38e">

**Comment by lxg20082008** [comment]
After many times test on Windows 10 Edge and Chrome. I find: open and clean the browser, first connect http://localhost:8123 is OK. But if refreshing the page or  connect http://localhost:8123 again, the "Custom element doesn't exist: homepage-card." occurs, and rmains even  with clearing all caches, etc. 
Home Assistant 2023.9.1

**Comment by derekcentrico** [comment]
2023.9.2 just installed and I didn't have an error when I opened the dashboard.  I thought SWEET.  Went back and opened it again 30 minutes later - error is back.  Very strange.

**Comment by AchimGrolimund** [comment]
Same Issue for me.

Win11 Enterprice 10.0.22000 Build 22000
Chrome Version 117.0.5938.63 (Offizieller Build) (64-Bit)
Home Assistant 2023.9.2
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230911.0 - latest

HA is Running in a VM inside Proxmox.

Sometimes i see the Icons relod, i see the Message:
![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/22026079/e26ade6d-e47c-4ed9-8633-18fe7847362a)

after 2 3 reloads, i see the icons again.

i found this in the Logs:
```
2023-09-13 15:17:15.376 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-13 15:20:01.870 WARNING (MainThread) [custom_components.dwains_dashboard] Update_listener called
```

and here in the Browser:
![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/22026079/8bdf9cbf-5da0-44b5-9f59-e80b5613cfbe)


![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/22026079/bfcccfb0-4523-47c7-b2ea-9b283a579bec)

**Comment by tanbronson** [comment]
I had a similar experience of failure, working, and now back to failure. I'm on mint Linux w/chrome.
I just upgraded to 2023.09.2, and the error "reappeared" on my Linux machine.
Android has continued to work for me

**Comment by TrialMaster** [comment]
> No issues with Windows 11 and iOS devices.

Windows 11 playing up now. I’ve reverted to 2023.8.4 for now

https://community.home-assistant.io/t/dwains-dashboard-1-click-install-dashboard-for-desktop-tablet-and-mobile-v3-1-0/168593/2522

**Comment by videologic2** [comment]
Following this. I have the same issue

**Comment by jpalenz77** [comment]
same here!

**Comment by dwainscheeren** [comment]
Please try this beta version 3.5.0 https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.5.0

**Comment by jpalenz77** [comment]
fixed here, thanks very much

**Comment by Shenharo** [comment]
> Please try this beta version 3.5.0 https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.5.0

@dwainscheeren 
This issue is fixed, but on mobile(Android) the menu moved to the bottom and I can't exit DD

**Comment by dwainscheeren** [comment]
The menu in DD was always in the bottom if you had in the top it was a bug. Swipe from left to get the HA menu itself.

**Comment by GTunney** [comment]
> The menu in DD was always in the bottom if you had in the top it was a bug. Swipe from left to get the HA menu itself.

Very strange my menu has always been at the top and still is after upgrading to 3.5.0

**Comment by dwainscheeren** [comment]
On desktop its on top and on mobile its at bottom by design.

**Comment by jakesie1309** [comment]
Hi Dwaine

Thanx for the fix. Looks to be working fine. Thanx again for the quick turn around time on this issue

**Comment by Shenharo** [comment]
But the menu button is nor working ( the HA one). DD is working just fine, but nothing else does

**Comment by rosicenko** [comment]
Same here. I also had it at top before on phone. Now I have there just grey empty bar and HA button is not working. So I am unable to get anywhere from dashboard.

**Comment by dwainscheeren** [comment]
Yes I need to check that, it's a new bug. For now you can just swipe from left to reveal the main HA app menu.

**Comment by Inkblot720** [comment]
> Please try this beta version 3.5.0 https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.5.0

So should I just enter that link as a custom repository in HACS

**Comment by Sythsaz** [comment]
> > Please try this beta version 3.5.0 https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.5.0
> 
> So should I just enter that link as a custom repository in HACS

You can go to HACS -> Dwains Dashboard -> 3-dot menu in the upper right -> show beta -> after it loads select the latest version

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/53737244/850919dc-e51e-4278-9b62-2ea0c38c4cbd)

**Comment by tanbronson** [comment]
I switched the beta version, and my linux machine is happy again!

**Comment by FeldFortress** [comment]
> Yes I need to check that, it's a new bug. For now you can just swipe from left to reveal the main HA app menu.

The swipe from left to reveal HA sidebar doesn't work on devices where swiping from left navigates back in the OS, it just closes the HA app and goes back to the Android home screen... I am now stuck in DD when opening the HA app.  Going to have to revert back from 3.5.0 which is a bummer because it finally put the DD navigation buttons on the bottom of the screen where I could reach them with one hand!

**Comment by Shenharo** [comment]
@InfiniteFeld  I added a button that navigate to a different dashboard for now

**Comment by FeldFortress** [comment]
@Shenharo that was a great workaround idea, thanks!

**Comment by rd5802** [comment]
> > > Please try this beta version 3.5.0 https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.5.0
> > 
> > 
> > So should I just enter that link as a custom repository in HACS
> 
> You can go to HACS -> Dwains Dashboard -> 3-dot menu in the upper right -> show beta -> after it loads select the latest version
> 
> ![image](https://user-images.githubusercontent.com/53737244/268996140-850919dc-e51e-4278-9b62-2ea0c38c4cbd.png)

Hello,
unfortunatelyy din`t help me.
* HA 2023.9.2
* browser cache clear


<img width="336" alt="image" src="https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/35902744/fcee5e0a-e9d7-4581-9862-ddf5d2fdfd71">

**Comment by Sythsaz** [comment]
> > > > Please try this beta version 3.5.0 https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.5.0
> 
> > > 
> 
> > > 
> 
> > > So should I just enter that link as a custom repository in HACS
> 
> > 
> 
> > You can go to HACS -> Dwains Dashboard -> 3-dot menu in the upper right -> show beta -> after it loads select the latest version
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/53737244/268996140-850919dc-e51e-4278-9b62-2ea0c38c4cbd.png)
> 
> 
> 
> Hello,
> 
> unfortunatelyy din`t help me.
> 
> * HA 2023.9.2
> 
> * browser cache clear
> 
> 
> 
> 
> 
> <img width="336" alt="image" src="https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/35902744/fcee5e0a-e9d7-4581-9862-ddf5d2fdfd71">
> 
> 

What device are you trying to use?

**Comment by rd5802** [comment]
> > > > > Please try this beta version 3.5.0 https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.5.0
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > So should I just enter that link as a custom repository in HACS
> > 
> > 
> > > 
> > 
> > 
> > > You can go to HACS -> Dwains Dashboard -> 3-dot menu in the upper right -> show beta -> after it loads select the latest version
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/53737244/268996140-850919dc-e51e-4278-9b62-2ea0c38c4cbd.png)
> > 
> > 
> > Hello,
> > unfortunatelyy din`t help me.
> > 
> > * HA 2023.9.2
> > * browser cache clear
> > 
> > <img alt="image" width="336" src="https://user-images.githubusercontent.com/35902744/270163131-fcee5e0a-e9d7-4581-9862-ddf5d2fdfd71.png">
> 
> What device are you trying to use?

What do you mean ?

**Comment by vikdb** [comment]
> > > Please try this beta version 3.5.0 https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.5.0
> > 
> > 
> > So should I just enter that link as a custom repository in HACS
> 
> You can go to HACS -> Dwains Dashboard -> 3-dot menu in the upper right -> show beta -> after it loads select the latest version
> 
> ![image](https://user-images.githubusercontent.com/53737244/268996140-850919dc-e51e-4278-9b62-2ea0c38c4cbd.png)

Do i need to remove DD from HACS and reinstall it to select the Beta? 
Because when i go to the 3 dots in HACS i dont see "show beta", only the options to redownload or open an issue..

**Comment by nocturneop15** [comment]
Confirm the latest beta **did not** fix the issue - tested on Vivaldi browser, MS Edge browser. It initially works when you drop the browser HTML5 cache, but it stop immediately after refresh. 

Currently playing with fresh new HA setup, so if I can help you diagnose this bug, let me know which logs may help you.

**Comment by pjanuario** [comment]
Running HA Container Build 2023.9.3 - DD 3.4.3 is still working for me without issues.

**Comment by Cook23** [comment]
> Yes I need to check that, it's a new bug. For now you can just swipe from left to reveal the main HA app menu.

Hello,

Still no solution for this bug ? From mobile APP there is no swipe from left.

Thanks.

**Comment by nocturneop15** [comment]
It started to work again with 2023.10 update of HA Supervisor. At least for me...

**Comment by rosicenko** [comment]
For me worked fine till last update. Now again is android app broken
![Screenshot_20231006-173006](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/127116844/f2f8c886-a2cb-4518-9f4d-c7f3727477ee)

**Comment by n0bbi** [comment]
For me it helped to delete the app cache.

**Comment by Solarflor** [comment]
Hello,
I have just downloaded the dashboard but it is not working showing the same message
![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/100423265/68b264db-2061-4da6-bfae-363e685cf603)
on all the browsers (Chrome, Edge, Apple) 

The HA log file:
`2023-10-07 19:57:25.785 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Comment by Markeydoo** [comment]
After updating to 3.5 I still have the issue on Windows 11 Pro with the Opera browser.

**Comment by lennon101** [comment]
> After updating to 3.5 I still have the issue on Windows 11 Pro with the Opera browser.

Ctl-F5 seems to fix this for me. It does pop up quite often but a quick refresh of the broswer cache using Ctl-F5 fixes it

**Comment by laolaxyz** [comment]
I am new to Home Assistant. However, I installed DD and on the Windows11 machine everything works. However no chance with the Android app - even after clean cache several times. I updated to 3.5.0 - no change... :-( So any other idea how to fix this ?
I set up the system 2 day ago - so everything should be updated to the most recent status.

**Comment by dwainscheeren** [comment]
This is fixed in 3.5.0 make sure you clear cache, reboot ha en make sure all is reset

**Comment by TrialMaster** [comment]
> This is fixed in 3.5.0 make sure you clear cache, reboot ha en make sure all is reset

This doesn’t work. A new release is required.

**Comment by lennon101** [comment]
> This is fixed in 3.5.0 make sure you clear cache, reboot ha en make sure all is reset

I concur. 3.5.0 did not fix the issue for me either.

**Comment by sla89** [comment]
@dwainscheeren I am also facing this issue.
I am using your latest release 3.5.0 and Home Assistant 2023.10.3

I get the following error:
```
dwains-dashboard.js:366 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'shadowRoot')
    at window.dwains_dashboard._dwains_navbar (dwains-dashboard.js:366:18)
    at window.dwains_dashboard._locationChanged (dwains-dashboard.js:298:20)
    at o (fire_event.ts:76:8)
    at s (navigate.ts:43:3)
    at o.value (hui-root.ts:827:7)
    at o.value (hui-root.ts:877:12)
    at F.handleEvent (lit-html.ts:2018:29)
    at i.fire (legacy-element-mixin.js:577:18)
    at i._itemActivate (iron-selectable.js:391:15)
    at i._activateHandler (iron-selectable.js:383:14)
```

**Comment by sbik38** [comment]
Same for me here but with "Atomic Calandar Revive". Everything was working fine till I updated to 2023.11 and recent update also from "Atomic Calendar". Everything is OK on my Win10 Computer, but I'm getting now the famous "Custom element doesn"t exist" on my Android tablet running Fullykiosk. I tried the delete Cash from Fullykiosk but problem is still there....

**Comment by anortiz08** [comment]
Same issue here on Android app. Has anyone been able to resolve this issue?

**Comment by jemmiegod** [comment]
After the initial install of DD 3.7, both browser and phone were in this broken state. Refresh of the browser resolved it on the PC however the HA android app refused to load the DD. I gave up on it. It started working in the HA app randomly a few hours later. Over night the HA android app updated and now DD is broken again. No amount of cache clearing resolves the issue.
This problem is still very much alive and present.

**Comment by NordicMitch** [comment]
Yep, still got the problem on the android app. 
![Screenshot_20240512-141206](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/163507733/cae4acf5-aa40-41b9-b001-70863dfcbd56)

**Comment by jr-ratliff** [comment]
I am also getting this error randomly on a S22 Android:

"Custom Element Doesn't exist: Homepage-card  type: custom: homepage-card"

I have tried clearing cache, force closing HA and rebooting phone.  It will work again for a couple days then I have to try all over again.

DD 3.7
Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3
Frontend 20240501.1

Android 14

Anyone have any recommendations for something to try?

**Comment by ghost** [comment]
Happens to me several times every day but fairly easy to get out of. Not as big of problem as it used to be when you by mistake updated HA from an app.

**Comment by kelilive** [comment]
I encountered the same problem...

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/142982913/050c8914-41ed-43b9-afef-cd0405596e70)

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/142982913/876302a4-1f3b-4251-b796-f502e7dacda4)

**Comment by deezid** [comment]
Can confirm

**Comment by atechnical** [comment]
the only solution is not using Dwain's dashboard

**Comment by Atlas-Night-Out** [comment]
> It seems that 2023.9 breaks DD. I need to look into this

Has this been fixed yet? thanks

Or is there a way to go back as I did not do a backup as things are all failing anyway!

**Comment by Tsury** [comment]
Same here, Windows 11, latest Edge

**Comment by ghost** [comment]
Web and android app is no problem to get working again by a kill/restart Shift+F5. When you get it to work it normally lasts for some time 
iPhone/iPad on the other hand is more tricky.
Can take up to 20 kill/restarts to get it to work. It happens on EVERY start and a simple screensave can make the problem reoccur, so for Apple users, this is very critical at this stage.

**Comment by Atlas-Night-Out** [comment]
It seems to have started to work again not at all sure why or how all I did was update Aqara APP and made sure all other things were updated

**Comment by Its4Nik** [comment]
Got the same problems right now :(

**Comment by bedelaitre** [comment]
Same problem here with Windows 11 and Edge

Here's the log:
Enregistreur: frontend.js.modern.202410023
Source: components/system_log/__init__.py:331
S'est produit pour la première fois: 07:27:11 (8 occurrences)
Dernier enregistrement: 07:39:18

- Uncaught error from Edge 130.0.0.0 on Windows 10 TypeError: Illegal constructor (custom element class must be registered with global customElements registry to be newable) new window.HTMLElement (src/scoped-custom-element-registry.js:168:12) e=window,r=e.trustedTypes,h=r?r.emptyScript:"",o=e.reactiveElementPolyfillSupport,n={toAttribute(t,i){switch (/node_modules/@lit/reactive-element/reactive-element.js:6:552) t{constructor(){super (/node_modules/lit/node_modules/lit-element/lit-element.js:6:53) constructor (/src/dwains-navigation-card.js:109:8) (!root.shadowRoot.querySelector (/src/dwains-dashboard.js:152:59) buildDwainsNavigation (/src/dwains-dashboard.js:116:19) this.getLovelace (/src/dwains-dashboard.js:98:17)

- Uncaught error from Edge 130.0.0.0 on Windows 10 TypeError: Illegal constructor (custom element class must be registered with global customElements registry to be newable) new window.HTMLElement (src/scoped-custom-element-registry.js:168:12) e=window,r=e.trustedTypes,h=r?r.emptyScript:"",o=e.reactiveElementPolyfillSupport,n={toAttribute(t,i){switch (/node_modules/@lit/reactive-element/reactive-element.js:6:552) t{constructor(){super (/node_modules/lit/node_modules/lit-element/lit-element.js:6:53) constructor (/src/dwains-navigation-card.js:109:8) (!root.shadowRoot.querySelector (/src/dwains-dashboard.js:152:59) buildDwainsNavigation (/src/dwains-dashboard.js:116:19) path.substring (/src/dwains-dashboard.js:48:17) dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow.history.replaceState (src/common/navigate.ts:46:12) this.route!.prefix}/${path}?${addSearchParam (src/panels/lovelace/hui-root.ts:826:15)

**Comment by galgranov** [comment]
clearing cache and local storage worked for me

**Comment by VibroAxe** [comment]
> Same problem here with Windows 11 and Edge
> 
> Here's the log: Enregistreur: frontend.js.modern.202410023 Source: components/system_log/**init**.py:331 S'est produit pour la première fois: 07:27:11 (8 occurrences) Dernier enregistrement: 07:39:18
> 
> * Uncaught error from Edge 130.0.0.0 on Windows 10 TypeError: Illegal constructor (custom element class must be registered with global customElements registry to be newable) new window.HTMLElement (src/scoped-custom-element-registry.js:168:12) e=window,r=e.trustedTypes,h=r?r.emptyScript:"",o=e.reactiveElementPolyfillSupport,n={toAttribute(t,i){switch (/node_modules/@lit/reactive-element/reactive-element.js:6:552) t{constructor(){super (/node_modules/lit/node_modules/lit-element/lit-element.js:6:53) constructor (/src/dwains-navigation-card.js:109:8) (!root.shadowRoot.querySelector (/src/dwains-dashboard.js:152:59) buildDwainsNavigation (/src/dwains-dashboard.js:116:19) this.getLovelace (/src/dwains-dashboard.js:98:17)
> * Uncaught error from Edge 130.0.0.0 on Windows 10 TypeError: Illegal constructor (custom element class must be registered with global customElements registry to be newable) new window.HTMLElement (src/scoped-custom-element-registry.js:168:12) e=window,r=e.trustedTypes,h=r?r.emptyScript:"",o=e.reactiveElementPolyfillSupport,n={toAttribute(t,i){switch (/node_modules/@lit/reactive-element/reactive-element.js:6:552) t{constructor(){super (/node_modules/lit/node_modules/lit-element/lit-element.js:6:53) constructor (/src/dwains-navigation-card.js:109:8) (!root.shadowRoot.querySelector (/src/dwains-dashboard.js:152:59) buildDwainsNavigation (/src/dwains-dashboard.js:116:19) path.substring (/src/dwains-dashboard.js:48:17) dispatchEvent (src/common/dom/fire_event.ts:76:7) mainWindow.history.replaceState (src/common/navigate.ts:46:12) this.route!.prefix}/${path}?${addSearchParam (src/panels/lovelace/hui-root.ts:826:15)

I'm also having this issue and have the same Illegal Constructor messages in the console. @dwainscheeren is this worthy of a new issue to track, or do you want to reopen this one?
![{CA3C83BF-14D8-4F03-BD36-890012C580F1}](https://github.com/user-attachments/assets/af20756a-a575-4ef9-ad68-1d925fedeefa)

**Comment by YusufcanY** [comment]
clearing cache and local storage worked for me too
